language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.0
  - ruby-head
  - rbx-2
  - jruby

before_install: gem install bundler -v 1.11.2

matrix:
  allow_failures:
  - rvm: 1.9.3
  - rvm: rbx-2
  - rvm: jruby
  fast_finish: true
